Renamed filedialog1.cc to filedialog2.cc. Created new filedialog1 testing FileDialog class. Adjusted Makefile to recognize exit code 77 as being skipped.

diff --git a/tests/ui-interactive/Makefile.am b/tests/ui-interactive/Makefile.am
--- a/tests/ui-interactive/Makefile.am
+++ b/tests/ui-interactive/Makefile.am
@@ -2,9 +2,9 @@
 
 AUTOMAKE_OPTIONS = serial-tests
 
-check_PROGRAMS = input1 app1 checkbox1 dialog1 filedialog1 focus1	\
-inputbox1 listbox1 listbox2 lockscreen1 messagebox1 packremove		\
-radiobox1 resize3 resize4 resize5
+check_PROGRAMS = input1 app1 checkbox1 dialog1 filedialog1	\
+filedialog2 focus1 inputbox1 listbox1 listbox2 lockscreen1	\
+messagebox1 packremove radiobox1 resize3 resize4 resize5
 
 AM_DEFAULT_SOURCE_EXT = .cc
 
@@ -20,6 +20,11 @@ AM_LDFLAGS += $(LD_EXPORT_DYNAMIC)
 check-local: $(check_PROGRAMS)
 	for f in $(check_PROGRAMS) ; do \
 		$(LIBTOOL) --mode=execute env LD_PRELOAD="$(top_builddir)/tests/preloadlib/.libs/libtestpreload.so" $$f ; \
-		test "x$$?" = "x0" || { echo "*** $$f failed" ; exit 1 ; } ; \
+		retval=$$? ; \
+		if test "x$$retval" = "x77" ; then \
+			echo "*** $$f skipped" ; \
+		else \
+			test "x$$retval" = "x0" || { echo "*** $$f failed" ; exit 1 ; } ; \
+		fi ; \
 	done
 endif
